### PR TITLE
Google drive api upgrade

### PR DESCRIPTION
**Pull request by douglascrp**
A customer asked us to upgrade the Google Drive API to the v3 version, and so we did.

I hope you can accept this PR as a contribution to the project.

### CODE REVIEW

**Comment by douglascrp** [comment]
Hello.

How do you deal with errors like this?
It seems they are not related with the changes introduced by the PR.

Do I need to do anything more to have this PR evaluated and accepted?

**Comment by OpenPj** [comment]
Hi Douglas,
Thank you so much for this commit update but for the next release 2.27 we don't want to change any specific part of the code related to logic or connectors because we are recreating the entire release process from scratch.

Anyway part of your initial changes were included in ManifoldCF 2.12 and 2.23. I see that only the last commit is updating the Google Drive dependencies. 

We could evaluate this for ManifoldCF 2.28 so we have to hold on for this latest upgrade for the Google Drive Connector.
I created a specific ticket for this:
https://issues.apache.org/jira/browse/CONNECTORS-1758

**Comment by OpenPj** [comment]
Merged in the trunk, thank you so much for your contribution @douglascrp ! 😄

**Comment by OpenPj** [comment]
I had to revert all the commits of this pull request because it brakes the Ant build.
Probably because in the trunk now we have different dependencies for the vulnerability fix merged before. 
@douglascrp could you please try to rework a little bit this contribution in order to be compliant with the current trunk?

I think that there is a problem with some dependencies of the Google Drive API v3.
Thank you so much for your contribution!

**Comment by OpenPj** [comment]
I'm sorry maybe I found an issue with the HSQL db dependencies, please don't invest time to rework your contribution because the issue depends on another pull request. I'll let you know the result.

**Comment by OpenPj** [comment]
Resolved the dependency conflict related to HSQLDB and now I'm working on remerging again this contribution

**Comment by OpenPj** [comment]
Ok I merged again your pull request in the trunk and now it seems that everything is working correctly.
I have just reverted the HSQLDB dependency version updated from the vulnerability fix of another pull request.
@douglascrp could you please checkout the current trunk of ManifoldCF in order to test the Google Drive connector updated with API v3?

**Pull request merged**
