### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by gladyscarrizales**
Hi ... I have a first spanish translation for manifoldcf. Miss some other file. If you need it I will continue the translation

### CODE REVIEW

**Comment by gladyscarrizales** [comment]
Hello……I terminated the translation

**Comment by iorixxx** [comment]
Thanks @gladyscarrizales for the Spanish translation!
For your future contributions, can you please mention the JIRA issue (e.g. `CONNECTORS-1256`) in the pull request title? We would like to test whether this action will link jira issue and the pull request. 

Can you please close this pull request, if you feel like your present contribution is successfully propagated/reflected into the ManifoldCF source tree.
Thanks!

**Comment by gladyscarrizales** [comment]
hi iorixxx, can be useful keep it opened so I can update the translation for future works, what do you think?

**Comment by iorixxx** [comment]
Given that https://issues.apache.org/jira/browse/CONNECTORS-1256 is closed as resolved, future works  would be better handled in a new pull request (PR) / JIRA ticket.

**Comment by iorixxx** [comment]
Please see https://issues.apache.org/jira/browse/CONNECTORS-1258 for an example, where translation is being updated.

**Comment by OpenPj** [comment]
This pull request is currently included for a long time starting from ManifoldCF 2.3:
https://github.com/apache/manifoldcf/blob/trunk/CHANGES.txt#L947

**Pull request closed without merging**
